### ISSUE TITLE
Unused methods in ListJournalExports

### ISSUE THREAD

**Issue by ChrisJBurns** [aws-samples/amazon-qldb-dmv-sample-java#7]
Nothing major, but in the `ListJournalExports` file, there are two methods that are unused:
- `    public static List<JournalS3ExportDescription> listExports(final String name, final String nextToken)`
- `public static List<JournalS3ExportDescription> listExports()`

I can submit a quick PR that removes these unused methods to remove the noise from the code as there are three overloaded `listExports` methods.

C

**Comment by othonrsanchez** [comment]
Hi @ChrisJBurns ,

Method `public static List<JournalS3ExportDescription> listExports(final String name, final String nextToken)` is used mostly to illustrate how to list the exports of a journal when passing a token. The other one, `public static List<JournalS3ExportDescription> listExports()` exist to show how to get the list of all the exports of the account, not just one ledger. 

Thanks ,

Othon

**Comment by ChrisJBurns** [comment]
Ahh I see, no problems :+1:
